// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: api/interface.proto

package RicartAgrawala

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RicartAgrawalaClient is the client API for RicartAgrawala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaClient interface {
	Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RequestBack, error)
	Reply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*ReplyBack, error)
}

type ricartAgrawalaClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaClient(cc grpc.ClientConnInterface) RicartAgrawalaClient {
	return &ricartAgrawalaClient{cc}
}

func (c *ricartAgrawalaClient) Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RequestBack, error) {
	out := new(RequestBack)
	err := c.cc.Invoke(ctx, "/RicartAgrawala.RicartAgrawala/request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartAgrawalaClient) Reply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*ReplyBack, error) {
	out := new(ReplyBack)
	err := c.cc.Invoke(ctx, "/RicartAgrawala.RicartAgrawala/reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartAgrawalaServer is the server API for RicartAgrawala service.
// All implementations must embed UnimplementedRicartAgrawalaServer
// for forward compatibility
type RicartAgrawalaServer interface {
	Request(context.Context, *Request) (*RequestBack, error)
	Reply(context.Context, *Reply) (*ReplyBack, error)
	mustEmbedUnimplementedRicartAgrawalaServer()
}

// UnimplementedRicartAgrawalaServer must be embedded to have forward compatible implementations.
type UnimplementedRicartAgrawalaServer struct {
}

func (UnimplementedRicartAgrawalaServer) Request(context.Context, *Request) (*RequestBack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRicartAgrawalaServer) Reply(context.Context, *Reply) (*ReplyBack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedRicartAgrawalaServer) mustEmbedUnimplementedRicartAgrawalaServer() {}

// UnsafeRicartAgrawalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServer interface {
	mustEmbedUnimplementedRicartAgrawalaServer()
}

func RegisterRicartAgrawalaServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServer) {
	s.RegisterService(&RicartAgrawala_ServiceDesc, srv)
}

func _RicartAgrawala_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RicartAgrawala.RicartAgrawala/request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServer).Request(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartAgrawala_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RicartAgrawala.RicartAgrawala/reply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServer).Reply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartAgrawala_ServiceDesc is the grpc.ServiceDesc for RicartAgrawala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartAgrawala.RicartAgrawala",
	HandlerType: (*RicartAgrawalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request",
			Handler:    _RicartAgrawala_Request_Handler,
		},
		{
			MethodName: "reply",
			Handler:    _RicartAgrawala_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/interface.proto",
}
